version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_board
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boarddb
      MYSQL_USER: boarduser
      MYSQL_PASSWORD: boardpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
